In [1]:
import os
import pandas as pd
import numpy as np
import regex as re
import pythainlp

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from sklearn.svm import SVC
import tensorflow.keras as keras

In [2]:
from preprocessing import Word_Embedder
from preprocessing import Text_processing
from text_classification import Text_classification, Text_classification_for_prediction, count_based_model
from text_classification import prepare_data_for_text_classification, prepare_data_for_sequence_prediction

In [3]:
os.chdir('E:\\Coding_projects\\data\\NER\\BEST10\\Current\\all_without_sw_clean2')

In [4]:
tr = []
with open('BEST10_no_sw_tr.txt', 'r', encoding='utf8') as f:
    for line in f:
        line = line.strip()
        if line != '':
            tr.append(line)
te = []
with open('BEST10_no_sw_te.txt', 'r', encoding='utf8') as f:
    for line in f:
        line = line.strip()
        if line != '':
            te.append(line)

In [5]:
print(len(tr))
print(len(te))

17392
4020


In [6]:
os.chdir('E:\\Coding_projects\\Thai_NLP')

In [7]:
tp = Text_processing(max_len=64,min_len=5,min_len_character=2)

In [8]:
train = tp.preprocessing2(tr,do_padding=True)
test = tp.preprocessing2(te, do_padding=True)

In [9]:
train[1]

{'NR': 0,
 'VV': 1,
 'NN': 2,
 'DDEM': 3,
 'JJV': 4,
 'P': 5,
 'JJA': 6,
 'PINT': 7,
 'NEG': 8,
 'AUX': 9,
 'CNJ': 10,
 'ADV': 11,
 'FXN': 12,
 'PDT': 13,
 'CL': 14,
 'OD': 15,
 'COMP': 16,
 'REFX': 17,
 'VA': 18,
 'FXG': 19,
 'DINT': 20,
 'PPER': 21,
 'PDEM': 22,
 'CD': 23,
 'PAR': 24,
 'DPER': 25,
 'FXAV': 26,
 'FXAJ': 27,
 'FWV': 28,
 'FWA': 29,
 'FWN': 30,
 'PU': 31,
 'IJ': 32,
 'blank': 33,
 'FWX': 34,
 '': 35}

In [10]:
train[1]['-PAD-'] = len(train[1])
tmp = prepare_data_for_sequence_prediction(train,
                                           test,
                                           max_len=64,
                                           min_len=5,
                                           unique_labels = train[1])

In [11]:
keras.backend.clear_session()

In [12]:
tc = Text_classification(prepared_data_dict=tmp,
                         do_deep_learning=True,
                         do_linear_classifier=False,
                         is_sequence_prediciton=True,
                         model_path='sequence_prediction')

Created the path: trained_models\sequence_prediction
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
word_vectors (InputLayer)       [(None, 64, 300)]    0                                            
__________________________________________________________________________________________________
masks (InputLayer)              [(None, 64)]         0                                            
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 64, 256)      330240      word_vectors[0][0]               
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 64, 256)      296448      bidirectional[0][0]              
_________________________________________

In [13]:
tc.fit_deep_learning()

Epoch 1/500
272/272 [==============================] - 34s 126ms/step - loss: 3.3345 - val_loss: 2.8356 - lr: 0.0010
Epoch 2/500
272/272 [==============================] - 29s 108ms/step - loss: 1.5111 - val_loss: 2.5049 - lr: 0.0010
Epoch 3/500
272/272 [==============================] - 29s 108ms/step - loss: 1.3691 - val_loss: 1.2179 - lr: 0.0010
Epoch 4/500
272/272 [==============================] - 29s 106ms/step - loss: 1.3194 - val_loss: 0.9848 - lr: 0.0010
Epoch 5/500
272/272 [==============================] - 28s 103ms/step - loss: 1.2910 - val_loss: 0.9561 - lr: 0.0010
Epoch 6/500
272/272 [==============================] - 28s 103ms/step - loss: 1.2629 - val_loss: 0.9161 - lr: 0.0010
Epoch 7/500
272/272 [==============================] - 30s 110ms/step - loss: 1.2459 - val_loss: 0.8958 - lr: 0.0010
Epoch 8/500
272/272 [==============================] - 39s 142ms/step - loss: 1.2259 - val_loss: 0.8932 - lr: 0.0010
Epoch 9/500
272/272 [==============================] - 46s 169ms

272/272 [==============================] - 46s 167ms/step - loss: 0.8222 - val_loss: 0.5680 - lr: 0.0010
Epoch 71/500
272/272 [==============================] - 51s 186ms/step - loss: 0.8194 - val_loss: 0.5617 - lr: 0.0010
Epoch 72/500
272/272 [==============================] - 45s 164ms/step - loss: 0.8173 - val_loss: 0.5618 - lr: 0.0010
Epoch 73/500
272/272 [==============================] - 49s 182ms/step - loss: 0.8151 - val_loss: 0.5559 - lr: 0.0010
Epoch 74/500
272/272 [==============================] - 46s 167ms/step - loss: 0.8129 - val_loss: 0.5493 - lr: 0.0010
Epoch 75/500
272/272 [==============================] - 47s 174ms/step - loss: 0.8075 - val_loss: 0.5535 - lr: 0.0010
Epoch 76/500
272/272 [==============================] - 51s 187ms/step - loss: 0.8064 - val_loss: 0.5684 - lr: 0.0010
Epoch 77/500
272/272 [==============================] - 45s 167ms/step - loss: 0.8033 - val_loss: 0.5488 - lr: 0.0010
Epoch 78/500
272/272 [==============================] - 49s 182ms/ste

272/272 [==============================] - 45s 165ms/step - loss: 0.7087 - val_loss: 0.4842 - lr: 0.0010
Epoch 140/500
272/272 [==============================] - 45s 165ms/step - loss: 0.7070 - val_loss: 0.4853 - lr: 0.0010
Epoch 141/500
272/272 [==============================] - 45s 166ms/step - loss: 0.7071 - val_loss: 0.4784 - lr: 0.0010
Epoch 142/500
272/272 [==============================] - 45s 165ms/step - loss: 0.7059 - val_loss: 0.4804 - lr: 0.0010
Epoch 143/500
272/272 [==============================] - 45s 165ms/step - loss: 0.7062 - val_loss: 0.4796 - lr: 0.0010
Epoch 144/500
272/272 [==============================] - 45s 165ms/step - loss: 0.7033 - val_loss: 0.4782 - lr: 0.0010
Epoch 145/500
272/272 [==============================] - 45s 166ms/step - loss: 0.7042 - val_loss: 0.4855 - lr: 0.0010
Epoch 146/500
272/272 [==============================] - 45s 166ms/step - loss: 0.7020 - val_loss: 0.4769 - lr: 0.0010
Epoch 147/500
272/272 [==============================] - 45s 1

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [16]:
a = np.array([[[1,2,3],[1,12,7]],[[3,2,1],[2,2,2]]])
print(a.shape)
print(a)

(2, 2, 3)
[[[ 1  2  3]
  [ 1 12  7]]

 [[ 3  2  1]
  [ 2  2  2]]]


In [24]:
print(np.argmax(a,axis=2))

[[2 1]
 [0 0]]


In [22]:
a.flatten()

array([ 1,  2,  3,  1, 12,  7,  3,  2,  1,  2,  2,  2])